### ISSUE TITLE
NavigationMiddleware: Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by jimmyff** [flutterings/flutter_redux_navigation#27]
I've suddenly started getting the following error:

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
W/FlutterActivityAndFragmentDelegate( 2981): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Connecting to VM Service at ws://127.0.0.1:41783/fLHvG1Kl8u4=/ws
E/flutter ( 2981): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 2981): #0      NavigationMiddleware.call
E/flutter ( 2981): #1      Store._createDispatchers.<anonymous closure>
E/flutter ( 2981): #2      LoggingMiddleware.call
E/flutter ( 2981): #3      Store._createDispatchers.<anonymous closure>
E/flutter ( 2981): #4      Store.dispatch
E/flutter ( 2981): #5      AuthMiddleware._handleAuthenticationStatusChanged
E/flutter ( 2981): #6      AuthMiddleware.call
E/flutter ( 2981): #7      Store._createDispatchers.<anonymous closure>
E/flutter ( 2981): #8      NavigationMiddleware.call
E/flutter ( 2981): #9      Store._createDispatchers.<anonymous closure>
E/flutter ( 2981): #10     LoggingMiddleware.call
E/flutter ( 2981): #11     Store._createDispatchers.<anonymous closure>
E/flutter ( 2981): #12     Store.dispatch
E/flutter ( 2981): #13     AuthMiddleware.call.<anonymous closure>
E/flutter ( 2981): #14     FbAuth.authProfile=
E/flutter ( 2981): #15     FbAuth._onAuthStateChanged
E/flutter ( 2981): #16     FbAuth.init.<anonymous closure>
E/flutter ( 2981): #17     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 2981): #18     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 2981): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 2981): #20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 2981): #21     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 2981): #22     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:25)
E/flutter ( 2981): #23     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
E/flutter ( 2981): #24     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:475:11)
E/flutter ( 2981): #25     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 2981): #26     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 2981): #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 2981): #28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 2981): #29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 2981): #30     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter ( 2981): #31     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter ( 2981): #32     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 2981): #33     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 2981): #34     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 2981): #35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 2981): #36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 2981): #37     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter ( 2981): #38     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter ( 2981): #39     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter ( 2981): #40     _rootRun (dart:async/zone.dart:1420:47)
E/flutter ( 2981): #41     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 2981): #42     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 2981): #43     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 2981): #44     _rootRun (dart:async/zone.dart:1428:13)
E/flutter ( 2981): #45     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 2981): #46     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 2981): #47     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 2981): #48     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 2981): #49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter ( 2981):
```

item 4 in the stacktrace relates to this line in my project:
```dart
        store.dispatch(NavigateToAction.pushNamedAndRemoveUntil(
            WelcomeScreen.route, (route) => false));
```

Any idea why this has started happening?

Thanks

**Comment by PapaTutuWawa** [comment]
I had the same problem. For me, it was fixed by adding `navigatorKey: NavigatorHolder.navigatorKey` to my `MaterialApp`. It is in the [example](https://github.com/flutterings/flutter_redux_navigation/blob/master/example/simple_login/lib/src/simple_login_app.dart#L18). I overlooked it when I first added it to my code.

**EDIT**: I also did not see the *suddenly* in your issue. Not sure if we have/had the same issue.

**Comment by jimmyff** [comment]
I'm still having issues with this and it has proven very tricky to track down and replicate. I've received numerous bad reviews in the app stores because of it. For reasons currently unknown to me, on rare occassions my app gets in a state that triggers this error. Once the app gets in this state restarting the app does not recover from it.

Here is the debug log showing the issue that I've finally managed to capture:

```
2023-01-20 17:09:52.207 27747-28750/? I/flutter: 52:20 Firebase/FINE: Initalising remote config...
2023-01-20 17:09:52.207 27747-28750/? I/flutter: 52:20 RC/INFO: Initalising remote config...
2023-01-20 17:09:52.208 27747-28750/? I/flutter: 52:20 RC/INFO: Config has been fetched in last 24 hours, activating...
2023-01-20 17:09:52.232 27747-28750/? I/flutter: 52:23 Firebase/FINE: Initalising firestore...
2023-01-20 17:09:52.232 27747-28750/? I/flutter: 52:23 Fs/FINE: Initalised
2023-01-20 17:09:52.232 27747-28750/? I/flutter: 52:23 Firebase/FINE: Initalising stotage...
2023-01-20 17:09:52.232 27747-28750/? I/flutter: 52:23 Storage/FINE: Initalised
2023-01-20 17:09:52.232 27747-28750/? I/flutter: 52:23 Firebase/FINE: Creating auth...
2023-01-20 17:09:52.233 27747-28750/? I/flutter: 52:23 NOTIFICATIONS/FINE: Notification config initalised
2023-01-20 17:09:52.241 27747-28750/? I/flutter: NOTIFICATIONS: Token FCM: eIQbrxPZRZSp53O21Cs2tJ:APA91bFBu6pVuO2dvY_DDAsOi1-yYdK_sFnYPJB_uuHz3wMFml7ye
2023-01-20 17:09:52.241 27747-28750/? I/flutter: 52:24 NOTIFICATIONS/SHOUT: NOTIFICATIONS: Do FCM stuff...
2023-01-20 17:09:52.249 27747-28750/? I/flutter: 52:24 DeviceMiddleware/INFO: InitAction
2023-01-20 17:09:52.249 27747-28750/? I/flutter: loading device id...
2023-01-20 17:09:52.249 27747-28750/? I/flutter: 52:24 AuthMiddleware/INFO: InitAction
2023-01-20 17:09:52.249 27747-28750/? I/flutter: 52:24 Auth/FINE: Initalising...
2023-01-20 17:09:52.249 27747-28750/? I/flutter: 52:24 AuthMiddleware/FINE: Initalised Auth...
2023-01-20 17:09:52.249 27747-28750/? I/flutter: 52:24 RemoteConfigMiddleware/INFO: InitAction
2023-01-20 17:09:52.249 27747-28750/? I/flutter: 52:24 RemoteConfigMiddleware/FINE: Remote Config is initalised!
2023-01-20 17:09:52.249 27747-28750/? I/flutter: 52:24 BillingMiddleware/FINE: Day timer setup, tomorrow: 24607 seconds...
2023-01-20 17:09:52.250 27747-28750/? I/flutter: 52:25 Redux/INFO: 17:9:52.250 [DISPATCH] InitAction
2023-01-20 17:09:52.250 27747-28750/? I/flutter: 52:25 Redux/INFO: 17:9:52.250 [DISPATCH] InitStateAction
2023-01-20 17:09:52.250 27747-28750/? I/flutter: Loading locale: en
2023-01-20 17:09:52.256 27747-28750/? I/flutter: 52:25 Auth/INFO: Setting Auth Profile, status=AuthState.notAuthenticated phone=null
2023-01-20 17:09:52.256 27747-28750/? I/flutter: 52:25 userReducer/FINE: State updated with AuthProfile object null
2023-01-20 17:09:52.256 27747-28750/? I/flutter: 52:25 Redux/INFO: 17:9:52.256 [DISPATCH] AuthSessionChangeAction
2023-01-20 17:09:52.256 27747-28750/? I/flutter: 52:25 AuthMiddleware/INFO: Handling auth change. State: AuthState.notAuthenticated
2023-01-20 17:09:52.256 27747-28750/? I/flutter: Auth profile changed: AuthState.notAuthenticated
2023-01-20 17:09:52.256 27747-28750/? E/flutter: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
    #0      NavigationMiddleware.call (package:flutter_redux_navigation/src/navigation_middleware.dart:47)
    #1      Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255)
    #2      LoggingMiddleware.call (package:redux_logging/redux_logging.dart:120)
    #3      Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255)
    #4      thunkMiddleware (package:redux_thunk/redux_thunk.dart:49)
    #5      Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255)
    #6      Store.dispatch (package:redux/src/store.dart:267)
    #7      AuthMiddleware._handleAuthenticationStatusChanged (package:onesceneapp/redux/middleware/auth_middleware.dart:195)
    #8      AuthMiddleware.call (package:onesceneapp/redux/middleware/auth_middleware.dart:133)
    <asynchronous suspension>
    #9      DeviceMiddleware.call (package:onesceneapp/redux/middleware/device_middleware.dart:35)
    <asynchronous suspension>
```

The app seems to initalise correctly, it dispatches AuthSessionChanged as the app now knows the user is not authenticated. The next step would be to navigate the user to the authentication screen. In the stack trace it mentions auth_middleware.dart:195, this is my code that is triggering the exception:
```dart
          store.dispatch(NavigateToAction.pushNamedAndRemoveUntil(
              WelcomeScreen.route, (route) => false));
```

My Material app is creating correctly and I certainly have the `navigatorKey: NavigatorHolder.navigatorKey` code in place.

@esarbanis I don't suppose you have any ideas?

**Comment by jimmyff** [comment]
This is the code that is failing (`navigation_middleware.dart:47`):
```
  currentState!.pushNamedAndRemoveUntil(
              navigationAction.name!, navigationAction.predicate!,
              arguments: navigationAction.arguments);
```
Here currentState is set:
```
      final currentState =
          this.currentState ?? NavigatorHolder.navigatorKey.currentState;
```
Is there anything extra I can do to ensure that NavigatorHolder.navigatorKey.currentState isn't null?

**Comment by jimmyff** [comment]
I think I might have tracked it down and it looks like an issue with my initalisation sequence. Despite the `initAction` being called by `MaterialApp` from it's `initState` method I dont think the `MaterialApp` had yet navigated to the `initialRoute` hence the error. I guess it's a timing issue and most devices had provided the `initialRoute` before the `initAction` tried to navigate them away from it.

**Comment by jimmyff** [comment]
> I think I might have tracked it down and it looks like an issue with my initalisation sequence. Despite the `initAction` being called by `MaterialApp` from it's `initState` method I dont think the `MaterialApp` had yet navigated to the `initialRoute` hence the error. I guess it's a timing issue and most devices had provided the `initialRoute` before the `initAction` tried to navigate them away from it.

This was the issue in my case.

Thanks

**Comment by bigbn** [comment]
I had the same issue with the same error. 
Resolved it using `onReady` callback of `GetMaterialApp` constructor. Problem has gone.
If dispatch to action happens before this event context can be null.
